### ISSUE TITLE
Debug info in django shell

### ISSUE THREAD

**Issue by Ritmix3300** [davidhalter/parso#23]
Hi.
When I use Django shell and try to use autocomplete I see this strings.
```
diff parser start
diff parser calculated                                                                        
diff: line_lengths old: 1, new: 1                                                             
diff replace old[1:1] new[1:1]                                                                
parse_part from 1 to 1 (to 0 in part parser)                                                  
diff parser end
```
Does your parser use the same logger as Django default?
I use Python 3.6.3, Django 1.10 and Ipython 6.2.1 which installed your package.

Can you change logger to prevent make output noise?

**Comment by davidhalter** [comment]
This was already fixed in parso `0.1.1`.

**Comment by Ritmix3300** [comment]
I read previous issues and updated parso to 0.1.1 but still have this problem.
There are no noise messages in IPython but in Django shell.

**Comment by davidhalter** [comment]
Since you have probably configured logging in a way that debug logs appear, you have to configure the parso logger to get ignored. That's your problem ;)

**Comment by zhongxiang117** [comment]
Hi, you can use the command: `scrapy shell _url_ --nolog` to override the debug information print out

**Comment by dopeboy** [comment]
I'm still seeing this on 0.1.1. As a workaround, I added

```
        'parso': {                                                                          
          'propagate': False,                                                                
        } 
```

to `LOGGING` and that did the trick.
